# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: wheels
on: push

jobs:

### build ######################################################################

  build:
    runs-on: macos-10.15
    env:
      MIBAP_JOB: 1329506437
      MIBAP_VER: "0.49"
      PKG_DIR: /var/cache/pkgs
    steps:

    #------------------------------------- get wheels from mibap's GitLab mirror

    - name: download artifact from GitLab
      run: curl -O -L https://gitlab.com/dehesselle/mibap/-/jobs/$MIBAP_JOB/artifacts/raw/mibap_v$MIBAP_VER.dmg

    - name: extract wheels
      run: |
        hdiutil attach mibap_v$MIBAP_VER.dmg
        cp /Volumes/mibap_v$MIBAP_VER/$PKG_DIR/*.whl $GITHUB_WORKSPACE
        hdiutil eject /Volumes/mibap_v$MIBAP_VER

    - name: log checksums
      run: |
        shasum -a 256 *.whl > wheels.sha256
        cat wheels.sha256

    #---------------------------------------------------------- upload artifacts

    - name: upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: Inkscape_wheels
        path: |
          ${{ github.workspace }}/*.whl
          ${{ github.workspace }}/wheels.sha256

### release ####################################################################

  release:
    runs-on: macos-10.15
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

    #---------------------------------------------------- create release archive

    - name: download wheels artifact
      uses: actions/download-artifact@v2
      with:
        name: Inkscape_wheels

    - name: create release archive
      run: tar cpJf wheels.tar.xz *.whl

    #------------------------------------------------------------ create release

    - name: create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Inkscape wheels for ${{ github.ref }}
        draft: true
        prerelease: false

    - name: upload archive to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: wheels.tar.xz
        asset_name: wheels.tar.xz
        asset_content_type: application/octet-stream
